### ISSUE TITLE
Creating GUI Components

### ISSUE THREAD

**Issue by Caellian** [NOVA-Team/NOVA-GUI#3]
I am considering of switching my mod to NOVA, but I can see that there are currently 3 components in NOVA-GUI. Do you mind if I fork this repo and write default Swing GUI components?
They will not be based on Swing, I will just write (as many) components that exist in swing.

**Comment by calclavia** [comment]
@Caellian Feel free to fork all your want and improve on this. @Victorious3 doesn't seem to be actively working on it.

**Comment by Caellian** [comment]
I will however start with components needed by my mod (TextField, TextArea, ...) first and then add other ones like RadioButtons and such.

**Comment by Victorious3** [comment]
I have a text area from one of my mods that I'm planning to move over, its almost a second Notepad++ (https://github.com/Victorious3/Integrated-Circuits/blob/master/src/main/java/moe/nightfall/vic/integratedcircuits/client/gui/component/GuiTextArea.java), has selection, tab indent, copy paste... But feel free to create the rest of it.

**Comment by Caellian** [comment]
That is amazing. Do you mind if I add selection highlighting and some more features like word selection and stuff. I've basically also written code for this already (based on MC code) [here](https://gist.github.com/Caellian/3c0fa5b6dc053924a855), but it's really broken when it comes to typing and does some weir things...

Sadly, I'll can't do anything until I set up my Arch Linux properly because I can't stand using Windows. So I'll start writing code in a day or two. I really look forward to helping with GUI.

**Comment by Victorious3** [comment]
It has selection highlighting, even word selection and line selection (single, double, triple-click). It also works with colors at is is highlighting in the complementary color using some OpenGL-trick (Have to see how I change that to support NOVA, but it shouldn't be a problem). Have a look at the dev-branch, that one is complete.
