### ISSUE TITLE
Making everything renderable an instance of screen object.

### ISSUE THREAD

**Issue by Caellian** [NOVA-Team/NOVA-GUI#4]
Can we make everything, including the world renderer an instance of object called screen object?

I think this would be really useful and would actually help with performance in a lot of scenarios. 

Let's say someone creates a really complex gui with animations and stuff, but doesn't really need to render the world in background (some games might not even do it by default). You currently can't prevent the world from being rendered in the background. This (while aesthetically pleasing) decreases performance a lot. Someone might even want to replace the whole screen in which case rendering the world in the background, next to being useless might also break the gui. 

I'm not sure how possible this is in Minecraft, it might even be less possible in other games, but would be really useful. 

Screen objects would contain window resolution and other information. It would also have input methods, render method and probably isVisible method. One could layer multiple screen objects which would then be rendered in order they were added. Screen objects would be a base for gui frames (which means ability to layer gui frames).
In game overlays like toolbar, health bar and such would be components of a screen object (toggled with F1 key).

Management of what is displayed and what not would be unbelievably easier this way.

This is a huge design decision, so I guess vote and improve on this concept.

**Comment by Caellian** [comment]
Not sure if I said so, but Frames (gui windows) would extend or implement (maybe it could be an interface) screen objects.

**Comment by Victorious3** [comment]
I was planning something like that, the more interchangeable objects are, the better.

**Comment by Caellian** [comment]
Right?! I mean, making mod developers able to do with code what they want should be the main objective. Maybe someone wants to add a border around world renderer without actually cutting off the screen. Also, I was thinking, we should be able to apply OpenGL rendering functions before the screen object is rendered and remove them after.
